/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.faculdade.imepac.UI.visualizar;

import br.com.faculdade.imepac.UI.edicao.*;
import br.com.faculdade.imepac.UI.commons.ActionManager;
import br.com.faculdade.imepac.UI.commons.CommonMethods;
import br.com.faculdade.imepac.UI.commons.InitializeFields;
import br.com.faculdade.imepac.data_utility.Mask;
import br.com.faculdade.imepac.infraestrutura.Persistence;
import br.com.faculdade.imepac.entidade.pessoa.Escolaridade;
import br.com.faculdade.imepac.entidade.pessoa.Raca;
import br.com.faculdade.imepac.entidade.pessoa.EstadoCivil;
import br.com.faculdade.imepac.entidade.pessoa.Funcionario;
import br.com.faculdade.imepac.entidade.pessoa.Genero;
import br.com.faculdade.imepac.entidade.pessoa.Habilidade;
import br.com.faculdade.imepac.entidade.projeto.Projeto;
import br.com.faculdade.imepac.entidade.relacionamento.Relacionamento;
import br.com.faculdade.imepac.infraestrutura.JPAUtil;
import java.awt.Desktop;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Set;
import javax.persistence.EntityManager;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 * FormCadastro é uma classe que representa o formulário de cadastro de
 * funcionários.
 */
public class VisualizarDadosFuncionario extends JPanel {

    private Funcionario funcionario;
    private JFrame frame;
    private Projeto projeto;
    private Relacionamento relacionamento;

    public VisualizarDadosFuncionario(JFrame frame, Long id) {
        this.frame = frame;
        EntityManager em = JPAUtil.getEntityManager();
        Persistence ps = new Persistence(em);

        this.funcionario = ps.getEntity(Funcionario.class, id);

        initComponents(); // Inicializa os componentes do formulário 
        this.setOldValues();
        this.addActions();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabelCor = new javax.swing.JLabel();
        jCheckBoxStatus = new javax.swing.JCheckBox();
        jLabelCor1 = new javax.swing.JLabel();
        jLabelCor2 = new javax.swing.JLabel();
        jLabelCor4 = new javax.swing.JLabel();
        jLabelCor5 = new javax.swing.JLabel();
        jLabelCor6 = new javax.swing.JLabel();
        jLabelCor7 = new javax.swing.JLabel();
        jLabelCor8 = new javax.swing.JLabel();
        jLabelCor9 = new javax.swing.JLabel();
        jLabelCor10 = new javax.swing.JLabel();
        jLabelCor11 = new javax.swing.JLabel();
        jLabelCor12 = new javax.swing.JLabel();
        jLabelCor13 = new javax.swing.JLabel();
        jLabelCor14 = new javax.swing.JLabel();
        jButtonAbrirCarteiraDeTrabalho = new javax.swing.JButton();
        jButtonAbrirCurriculo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelCor15 = new javax.swing.JLabel();
        jLabelCor16 = new javax.swing.JLabel();
        jLabelCor17 = new javax.swing.JLabel();
        jLabelCor19 = new javax.swing.JLabel();
        jCheckBoxAcolhido = new javax.swing.JCheckBox();
        jCheckBoxVoluntario = new javax.swing.JCheckBox();
        jLabelCor18 = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelCpf = new javax.swing.JLabel();
        jLabelCores = new javax.swing.JLabel();
        jLabelCnh = new javax.swing.JLabel();
        jLabelDataNascimento = new javax.swing.JLabel();
        jLabelCep = new javax.swing.JLabel();
        jLabelProjeto = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelGenero = new javax.swing.JLabel();
        jLabelEscolaridade = new javax.swing.JLabel();
        jLabelMei = new javax.swing.JLabel();
        jLabelEstadoCivil = new javax.swing.JLabel();
        jLabelNumeroCelular = new javax.swing.JLabel();
        jLabelPeriodo = new javax.swing.JLabel();
        jLabelCargo = new javax.swing.JLabel();
        jLabelCargaHoraria = new javax.swing.JLabel();
        jLabelSalario1 = new javax.swing.JLabel();
        jLabelRg = new javax.swing.JLabel();
        jLabelCor20 = new javax.swing.JLabel();
        jCheckBoxExperienciaProfissionais = new javax.swing.JCheckBox();
        jButtonVerHabilidades = new javax.swing.JButton();
        jButtonVerProjetos = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jLabel8.setText("Data de Nascimento");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jLabel7.setText("CPF");

        jLabel9.setText("Nome");

        jLabel10.setText("RG");

        jLabel24.setText("CEP");

        jLabel26.setText("Número de celular");

        jTextField27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField27ActionPerformed(evt);
            }
        });

        jTextField21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField21ActionPerformed(evt);
            }
        });

        jTextField24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField24ActionPerformed(evt);
            }
        });

        jLabel30.setText("Cor");

        jLabel27.setText("Dados profissão");

        jLabel23.setText("Gênero");

        jLabel25.setText("Carteira de trabalho");

        jLabel29.setText("Currículo");

        jTextField26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField26ActionPerformed(evt);
            }
        });

        jLabel28.setText("E-mail");

        jTextField1.setText("jTextField1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabelCor.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelCor.setText("Numero celular:");

        jCheckBoxStatus.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCheckBoxStatus.setText("Ativo");
        jCheckBoxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxStatusActionPerformed(evt);
            }
        });

        jLabelCor1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelCor1.setText("Nome:");

        jLabelCor2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelCor2.setText("Data nascimento:");

        jLabelCor4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelCor4.setText("Currículo:");

        jLabelCor5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelCor5.setText("Projeto:");

        jLabelCor6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelCor6.setText("Escolaridade:");

        jLabelCor7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelCor7.setText("CEP:");

        jLabelCor8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelCor8.setText("Gênero:");

        jLabelCor9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelCor9.setText("CPF:");

        jLabelCor10.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelCor10.setText("CNH:");

        jLabelCor11.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelCor11.setText("Cor:");

        jLabelCor12.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelCor12.setText("MEI:");

        jLabelCor13.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelCor13.setText("Estado-civil:");

        jLabelCor14.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelCor14.setText("Carteira de trabalho:");

        jButtonAbrirCarteiraDeTrabalho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/carteira-de-identidade (1).png"))); // NOI18N
        jButtonAbrirCarteiraDeTrabalho.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonAbrirCurriculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/curriculo.png"))); // NOI18N
        jButtonAbrirCurriculo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel3.setText("Dados profissionais:");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel4.setText("Dados pessoais:");

        jLabelCor15.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelCor15.setText("Período:");

        jLabelCor16.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelCor16.setText("Carga horária:");

        jLabelCor17.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelCor17.setText("Salário:");

        jLabelCor19.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelCor19.setText("Cargo:");

        jCheckBoxAcolhido.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCheckBoxAcolhido.setText("Acolhido");
        jCheckBoxAcolhido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAcolhidoActionPerformed(evt);
            }
        });

        jCheckBoxVoluntario.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCheckBoxVoluntario.setText("Voluntário");
        jCheckBoxVoluntario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxVoluntarioActionPerformed(evt);
            }
        });

        jLabelCor18.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelCor18.setText("E-mail:");

        jLabelNome.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelNome.setText("nome");

        jLabelCpf.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelCpf.setText("cpf");

        jLabelCores.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelCores.setText("cor");

        jLabelCnh.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelCnh.setText("cnh");

        jLabelDataNascimento.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelDataNascimento.setText("data nascimento");

        jLabelCep.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelCep.setText("cep");

        jLabelProjeto.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelProjeto.setText("projeto");

        jLabelEmail.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelEmail.setText("e-mail");

        jLabelGenero.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelGenero.setText("gênero");

        jLabelEscolaridade.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelEscolaridade.setText("escolaridade");

        jLabelMei.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelMei.setText("mei");

        jLabelEstadoCivil.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelEstadoCivil.setText("estado civil");

        jLabelNumeroCelular.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelNumeroCelular.setText("número celular");

        jLabelPeriodo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelPeriodo.setText("período");

        jLabelCargo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelCargo.setText("cargo");

        jLabelCargaHoraria.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelCargaHoraria.setText("cargo");

        jLabelSalario1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelSalario1.setText("salário");

        jLabelRg.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelRg.setText("rg");

        jLabelCor20.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelCor20.setText("RG:");

        jCheckBoxExperienciaProfissionais.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCheckBoxExperienciaProfissionais.setText("Possui experiência profissional");
        jCheckBoxExperienciaProfissionais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxExperienciaProfissionaisActionPerformed(evt);
            }
        });

        jButtonVerHabilidades.setBackground(new java.awt.Color(51, 156, 196));
        jButtonVerHabilidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/habilidades-interpessoais.png"))); // NOI18N
        jButtonVerHabilidades.setText("Habilidades");
        jButtonVerHabilidades.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonVerProjetos.setBackground(new java.awt.Color(14, 138, 134));
        jButtonVerProjetos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/casa-limpa.png"))); // NOI18N
        jButtonVerProjetos.setText("Projetos");
        jButtonVerProjetos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCor9)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelCpf))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCor2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelDataNascimento))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCor10)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelCnh))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCor7)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelCep))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCor1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelNome))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCor11)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelCores))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCor12)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelMei))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCor18)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelEmail))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCor8)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelGenero))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCor5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelProjeto)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButtonVerProjetos)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButtonVerHabilidades))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelCor4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButtonAbrirCurriculo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(jLabelCor14, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonAbrirCarteiraDeTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelCor20)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelRg))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelCor6)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelEscolaridade))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelCor)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelNumeroCelular))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelCor13)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelEstadoCivil))
                                    .addComponent(jCheckBoxStatus)
                                    .addComponent(jCheckBoxExperienciaProfissionais))))
                        .addGap(0, 411, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCor17)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelSalario1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCor15)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelPeriodo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCor19)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelCargo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCor16)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelCargaHoraria)))
                        .addGap(251, 251, 251)
                        .addComponent(jCheckBoxVoluntario)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxAcolhido)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(296, 296, 296)
                                .addComponent(jLabel1))
                            .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelCor6)
                                .addComponent(jLabelEscolaridade))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelCor1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelNome)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCor11)
                            .addComponent(jLabelCores)
                            .addComponent(jLabelCor20)
                            .addComponent(jLabelRg))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCor9)
                            .addComponent(jLabelCpf))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCor2)
                            .addComponent(jLabelDataNascimento)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCor)
                            .addComponent(jLabelNumeroCelular))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCor13)
                            .addComponent(jLabelEstadoCivil))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCor10)
                            .addComponent(jLabelCnh))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCor7)
                            .addComponent(jLabelCep)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBoxStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBoxExperienciaProfissionais)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCor14, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAbrirCarteiraDeTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCor4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAbrirCurriculo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonVerProjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonVerHabilidades, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCor18)
                            .addComponent(jLabelEmail))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCor8)
                            .addComponent(jLabelGenero))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCor5)
                            .addComponent(jLabelProjeto))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCor12)
                            .addComponent(jLabelMei))))
                .addGap(63, 63, 63)
                .addComponent(jLabel3)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBoxVoluntario)
                        .addComponent(jCheckBoxAcolhido))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelCor15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelPeriodo)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCor19)
                    .addComponent(jLabelCargo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCor17)
                    .addComponent(jLabelSalario1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCor16)
                    .addComponent(jLabelCargaHoraria))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField21ActionPerformed

    private void jTextField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField24ActionPerformed

    private void jTextField26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField26ActionPerformed

    private void jTextField27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField27ActionPerformed

    private void jCheckBoxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxStatusActionPerformed

    private void jCheckBoxAcolhidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAcolhidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxAcolhidoActionPerformed

    private void jCheckBoxVoluntarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxVoluntarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxVoluntarioActionPerformed

    private void jCheckBoxExperienciaProfissionaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxExperienciaProfissionaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxExperienciaProfissionaisActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbrirCarteiraDeTrabalho;
    private javax.swing.JButton jButtonAbrirCurriculo;
    private javax.swing.JButton jButtonVerHabilidades;
    private javax.swing.JButton jButtonVerProjetos;
    private javax.swing.JCheckBox jCheckBoxAcolhido;
    private javax.swing.JCheckBox jCheckBoxExperienciaProfissionais;
    private javax.swing.JCheckBox jCheckBoxStatus;
    private javax.swing.JCheckBox jCheckBoxVoluntario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCargaHoraria;
    private javax.swing.JLabel jLabelCargo;
    private javax.swing.JLabel jLabelCep;
    private javax.swing.JLabel jLabelCnh;
    private javax.swing.JLabel jLabelCor;
    private javax.swing.JLabel jLabelCor1;
    private javax.swing.JLabel jLabelCor10;
    private javax.swing.JLabel jLabelCor11;
    private javax.swing.JLabel jLabelCor12;
    private javax.swing.JLabel jLabelCor13;
    private javax.swing.JLabel jLabelCor14;
    private javax.swing.JLabel jLabelCor15;
    private javax.swing.JLabel jLabelCor16;
    private javax.swing.JLabel jLabelCor17;
    private javax.swing.JLabel jLabelCor18;
    private javax.swing.JLabel jLabelCor19;
    private javax.swing.JLabel jLabelCor2;
    private javax.swing.JLabel jLabelCor20;
    private javax.swing.JLabel jLabelCor4;
    private javax.swing.JLabel jLabelCor5;
    private javax.swing.JLabel jLabelCor6;
    private javax.swing.JLabel jLabelCor7;
    private javax.swing.JLabel jLabelCor8;
    private javax.swing.JLabel jLabelCor9;
    private javax.swing.JLabel jLabelCores;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelDataNascimento;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEscolaridade;
    private javax.swing.JLabel jLabelEstadoCivil;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelMei;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNumeroCelular;
    private javax.swing.JLabel jLabelPeriodo;
    private javax.swing.JLabel jLabelProjeto;
    private javax.swing.JLabel jLabelRg;
    private javax.swing.JLabel jLabelSalario1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables

    /**
     * Define os valores do funcionário com base nos campos do formulário.
     */
    public void setOldValues() {

        // Obtém os valores dos campos do formulário
        jLabelNome.setText(funcionario.getNome());
        jLabelCpf.setText(Mask.mascaraCpf(funcionario.getCpf()));
        jLabelRg.setText(funcionario.getRg());
        jLabelCnh.setText(funcionario.getCnh());
        jLabelEmail.setText(funcionario.getEmail());
        jLabelMei.setText(funcionario.getMei());
        jLabelCep.setText(Mask.mascaraCep(funcionario.getCep()));
        jCheckBoxStatus.setSelected(funcionario.isArquivado());
        jCheckBoxExperienciaProfissionais.setSelected(funcionario.isExperienciaProfissional());
        jLabelEmail.setText(funcionario.getEmail());
        jLabelGenero.setText(String.valueOf(funcionario.getGenero()).toLowerCase());

        // Cria um objeto DateTimeFormatter com o padrão desejado
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        // Formata a data
        String formattedDate = formatter.format(funcionario.getDataNascimento());

        jLabelDataNascimento.setText(formattedDate);

        if (funcionario.getRelacionamentos().size() != 0) {
            var relacionamentos = funcionario.getRelacionamentos();
            var relacionamento = relacionamentos.get(relacionamentos.size() - 1);
            this.projeto = relacionamento.getProjeto();
            jLabelProjeto.setText(this.projeto.getNome());

        }

        jLabelMei.setText(funcionario.getMei());
        jLabelNumeroCelular.setText(Mask.mascaraNumeroCelular(funcionario.getNumeroCelular()));
        jLabelEstadoCivil.setText(String.valueOf(funcionario.getEstadoCivil()).toLowerCase());
        jLabelEscolaridade.setText(String.valueOf(funcionario.getEscolaridade()).toLowerCase());
        jLabelRg.setText(funcionario.getRg());

        jLabelPeriodo.setText(String.valueOf(funcionario.getDadosProfissao().getPeriodo()).toLowerCase());
        jLabelCargo.setText(funcionario.getDadosProfissao().getCargo());

        var salario = funcionario.getDadosProfissao().getSalario() != null ? String.valueOf(funcionario.getDadosProfissao().getSalario()) : "voluntário";
        jLabelSalario1.setText(salario);

        jLabelCargaHoraria.setText(String.valueOf(funcionario.getDadosProfissao().getCargaHoraria()));
        jCheckBoxAcolhido.setSelected(funcionario.getDadosProfissao().isAcolhido());
        jCheckBoxVoluntario.setSelected(funcionario.getDadosProfissao().isVoluntario());

        jCheckBoxAcolhido.setEnabled(false); // Desabilita o JCheckBox
        jCheckBoxExperienciaProfissionais.setEnabled(false); // Desabilita o JCheckBox
        jCheckBoxStatus.setEnabled(false); // Desabilita o JCheckBox
        jCheckBoxVoluntario.setEnabled(false); // Desabilita o JCheckBox

    }

    public void addActions() {
        jButtonAbrirCurriculo.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                if (funcionario.getPathCurriculo() != null) {

                    File documento = new File(funcionario.getPathCurriculo());

                    if (Desktop.isDesktopSupported()) {
                        Desktop desktop = Desktop.getDesktop();
                        try {
                            // Verifica se o arquivo existe
                            if (documento.exists()) {
                                // Abre o documento com o aplicativo padrão
                                desktop.open(documento);
                            } else {
                                JOptionPane.showMessageDialog(null, "O arquivo não existe: " + funcionario.getPathCurriculo());
                            }
                        } catch (Exception erro) {
                            erro.printStackTrace();
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "A abertura de documentos não é suportada no ambiente atual.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Sem arquivo anexado.");
                }

            }
        });

        jButtonAbrirCarteiraDeTrabalho.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                if (funcionario.getPathCarteiraDeTrabalho() != null) {

                    File documento = new File(funcionario.getPathCarteiraDeTrabalho());

                    if (Desktop.isDesktopSupported()) {
                        Desktop desktop = Desktop.getDesktop();
                        try {
                            // Verifica se o arquivo existe
                            if (documento.exists()) {
                                // Abre o documento com o aplicativo padrão
                                desktop.open(documento);
                            } else {
                                JOptionPane.showMessageDialog(null, "O arquivo não existe: " + funcionario.getPathCarteiraDeTrabalho());
                            }
                        } catch (Exception erro) {
                            erro.printStackTrace();
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "A abertura de documentos não é suportada no ambiente atual.");
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Sem arquivo anexado.");

                }

            }
        }
        );

        jButtonVerHabilidades.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                DefaultTableModel modelo = new DefaultTableModel();

                modelo.addColumn("Habilidades");

                for (Habilidade habilidade : funcionario.getHabilidade()) {
                    modelo.addRow(new Object[]{habilidade.getHabilidade()
                    });
                }

                JTable table = new JTable(modelo);
                JScrollPane scrollPane = new JScrollPane(table);

                JFrame frame = new JFrame("Habilidades");
                frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                frame.setSize(500, 300);
                frame.add(scrollPane);
                frame.setVisible(true);
            }
        }
        );

        jButtonVerProjetos.addActionListener(
                new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                DefaultTableModel modelo = new DefaultTableModel();

                modelo.addColumn("Nome");
                modelo.addColumn("CEP");

                for (Relacionamento relacionamento : funcionario.getRelacionamentos()) {
                    modelo.addRow(new Object[]{relacionamento.getProjeto().getNome(),
                        relacionamento.getProjeto().getCep()
                    });
                }

                JTable table = new JTable(modelo);
                JScrollPane scrollPane = new JScrollPane(table);

                JFrame frame = new JFrame("Projetos");
                frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                frame.setSize(500, 300);
                frame.add(scrollPane);
                frame.setVisible(true);
            }
        }
        );
    }
}
