version: '3'

services:
  db:
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_DATABASE: casa_de_davi
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
