/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.faculdade.imepac.UI;

import br.com.faculdade.imepac.UI.commons.CommonMethods;
import br.com.faculdade.imepac.entidade.pessoa.Escolaridade;
import br.com.faculdade.imepac.entidade.pessoa.Funcionario;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class FormEscolaridade extends javax.swing.JPanel {

    private JFrame frame;
    private Funcionario funcionario;

    public FormEscolaridade(JFrame frame, Funcionario funcionario) {
        initComponents();
        this.frame = frame;
    }

    /**
     * Creates new form FormEscolaridade
     */
    public FormEscolaridade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDescricao = new javax.swing.JLabel();
        jButtonEducation = new javax.swing.JButton();
        jLabelEscolaridade1 = new javax.swing.JLabel();
        jTextFieldInstituicao = new javax.swing.JTextField();
        jCheckBoxGraduacao = new javax.swing.JCheckBox();
        jFormattedTextFieldDataInicioEscolaridade = new javax.swing.JFormattedTextField();
        jFormattedTextFieldDataFimEscolaridade = new javax.swing.JFormattedTextField();
        jTextFieldCurso = new javax.swing.JTextField();
        jLabelInstituicao = new javax.swing.JLabel();
        jLabelInstituicao1 = new javax.swing.JLabel();
        jLabelDataInicioEscolaridade = new javax.swing.JLabel();
        jLabelDataFimEscolaridade = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescricao = new javax.swing.JTextArea();

        jLabelDescricao.setText("Descrição");

        jButtonEducation.setText("Adicionar");
        jButtonEducation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonEducation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEducationActionPerformed(evt);
            }
        });

        jLabelEscolaridade1.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabelEscolaridade1.setText("Escolaridade");

        jCheckBoxGraduacao.setText("Graduação");
        jCheckBoxGraduacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxGraduacaoActionPerformed(evt);
            }
        });

        jFormattedTextFieldDataInicioEscolaridade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldDataInicioEscolaridadeActionPerformed(evt);
            }
        });

        jFormattedTextFieldDataFimEscolaridade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldDataFimEscolaridadeActionPerformed(evt);
            }
        });

        jLabelInstituicao.setText("Curso");

        jLabelInstituicao1.setText("Instituição");

        jLabelDataInicioEscolaridade.setText("Data de início");

        jLabelDataFimEscolaridade.setText("Data de encerramento");

        jTextAreaDescricao.setColumns(20);
        jTextAreaDescricao.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescricao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabelEscolaridade1)
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelInstituicao)
                                .addComponent(jTextFieldCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBoxGraduacao))
                            .addGap(101, 101, 101)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelDescricao)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelInstituicao1)
                                .addComponent(jTextFieldInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(102, 102, 102)
                                    .addComponent(jLabelDataInicioEscolaridade))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(101, 101, 101)
                                    .addComponent(jFormattedTextFieldDataInicioEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelDataFimEscolaridade)
                                .addComponent(jFormattedTextFieldDataFimEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(134, 134, 134)
                            .addComponent(jButtonEducation, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEscolaridade1)
                .addContainerGap(267, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelDataInicioEscolaridade)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelInstituicao1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldDataInicioEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldDataFimEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelDataFimEscolaridade)
                                .addGap(26, 26, 26))))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelDescricao)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(jLabelInstituicao)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jCheckBoxGraduacao)))
                    .addGap(35, 35, 35)
                    .addComponent(jButtonEducation, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEducationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEducationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEducationActionPerformed

    private void jCheckBoxGraduacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxGraduacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxGraduacaoActionPerformed

    private void jFormattedTextFieldDataInicioEscolaridadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDataInicioEscolaridadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldDataInicioEscolaridadeActionPerformed

    private void jFormattedTextFieldDataFimEscolaridadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDataFimEscolaridadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldDataFimEscolaridadeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEducation;
    private javax.swing.JCheckBox jCheckBoxGraduacao;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataFimEscolaridade;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataInicioEscolaridade;
    private javax.swing.JLabel jLabelDataFimEscolaridade;
    private javax.swing.JLabel jLabelDataInicioEscolaridade;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelEscolaridade1;
    private javax.swing.JLabel jLabelInstituicao;
    private javax.swing.JLabel jLabelInstituicao1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescricao;
    private javax.swing.JTextField jTextFieldCurso;
    private javax.swing.JTextField jTextFieldInstituicao;
    // End of variables declaration//GEN-END:variables

    /**
     * Limpa todos os campos de escolaridade.
     */
    public void clearFieldsEscolaridade() {
        jTextFieldInstituicao.setText("");
        jTextFieldCurso.setText("");
        jCheckBoxGraduacao.setSelected(false);
        jFormattedTextFieldDataInicioEscolaridade.setText("");
        jFormattedTextFieldDataFimEscolaridade.setText("");
        jTextAreaDescricao.setText("");
    }

    public void addEducationButton() {
        jButtonEducation.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    var escolaridade = new Escolaridade();
                    var instituicao = jTextFieldInstituicao.getText();
                    var curso = jTextFieldCurso.getText();
                    var graduacao = jCheckBoxGraduacao.isSelected();
                    LocalDate dataInicio = CommonMethods.parseStringToLocalDate(jFormattedTextFieldDataInicioEscolaridade.getText());
                    LocalDate dataFim = CommonMethods.parseStringToLocalDate(jFormattedTextFieldDataFimEscolaridade.getText());
                    var descricao = jTextAreaDescricao.getText();

                    escolaridade.setInstituicao(instituicao);
                    escolaridade.setCurso(curso);
                    escolaridade.setGraduacao(graduacao);
                    escolaridade.setPeriodoInicio(dataInicio);
                    escolaridade.setPeriodoFim(dataFim);
                    escolaridade.setDescricao(descricao);
                    escolaridade.setFuncionario(funcionario);

                    funcionario.adicionarEscolaridade(escolaridade);

                    clearFieldsEscolaridade();

                } catch (Exception error) {
                    JOptionPane.showMessageDialog(null, "Ocorreu um erro! " + error.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
    }
}
