/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.faculdade.imepac.UI.cadastro;

import br.com.faculdade.imepac.UI.commons.CommonMethods;
import br.com.faculdade.imepac.UI.edicao.FormDadosFuncionarioEdicao;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;

/**
 *
 * @author gusta
 */
public class PaginaInicial extends JFrame {

    /**
     * Creates new form PaginaInicial
     */
    JFrame currentFrame = this;

    public PaginaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenuCadastroFuncionario = new javax.swing.JMenu();
        jMenuItemCadastroFuncionario = new javax.swing.JMenuItem();
        jMenuItemEdicaoFuncionario = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemCadastroProjeto = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);

        jMenuBar2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jMenuBar2.setMargin(new java.awt.Insets(2, 2, 2, 2));

        jMenuCadastroFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/funcionario-principal-icone.png"))); // NOI18N
        jMenuCadastroFuncionario.setText("Funcionário");
        jMenuCadastroFuncionario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jMenuItemCadastroFuncionario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenuItemCadastroFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/funcionario-cadastro-icone.png"))); // NOI18N
        jMenuItemCadastroFuncionario.setText("Cadastro");
        jMenuCadastroFuncionario.add(jMenuItemCadastroFuncionario);

        jMenuItemEdicaoFuncionario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenuItemEdicaoFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/funcionario-editar-icone.png"))); // NOI18N
        jMenuItemEdicaoFuncionario.setText("Editar");
        jMenuItemEdicaoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEdicaoFuncionarioActionPerformed(evt);
            }
        });
        jMenuCadastroFuncionario.add(jMenuItemEdicaoFuncionario);

        jMenuItem3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/funcionario-listagem-icone.png"))); // NOI18N
        jMenuItem3.setText("Listagem");
        jMenuCadastroFuncionario.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/funcionario-deletar-icone.png"))); // NOI18N
        jMenuItem4.setText("Deletar");
        jMenuCadastroFuncionario.add(jMenuItem4);

        jMenuBar2.add(jMenuCadastroFuncionario);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/casa-principal-icone.png"))); // NOI18N
        jMenu4.setText("Projeto");
        jMenu4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jMenuItemCadastroProjeto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenuItemCadastroProjeto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/funcionario-cadastro-icone.png"))); // NOI18N
        jMenuItemCadastroProjeto.setText("Cadastro");
        jMenu4.add(jMenuItemCadastroProjeto);

        jMenuItem6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/funcionario-editar-icone.png"))); // NOI18N
        jMenuItem6.setText("Editar");
        jMenu4.add(jMenuItem6);

        jMenuItem7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/funcionario-listagem-icone.png"))); // NOI18N
        jMenuItem7.setText("Listagem");
        jMenu4.add(jMenuItem7);

        jMenuItem8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/funcionario-deletar-icone.png"))); // NOI18N
        jMenuItem8.setText("Deletar");
        jMenu4.add(jMenuItem8);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 929, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemEdicaoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEdicaoFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemEdicaoFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                var paginaInicial = new PaginaInicial();
                paginaInicial.addActions();

                paginaInicial.setDefaultCloseOperation(EXIT_ON_CLOSE);

                // Adicione seus componentes aqui...
                // Torna o JFrame visível
                paginaInicial.setVisible(true);

                // Configura o JFrame para abrir maximizado
                paginaInicial.setExtendedState(JFrame.MAXIMIZED_BOTH);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuCadastroFuncionario;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItemCadastroFuncionario;
    private javax.swing.JMenuItem jMenuItemCadastroProjeto;
    private javax.swing.JMenuItem jMenuItemEdicaoFuncionario;
    // End of variables declaration//GEN-END:variables

    public void addActions() {
        jMenuItemCadastroFuncionario.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                CommonMethods.goToNewPage(currentFrame, new FormDadosFuncionario(currentFrame));
            }
        });

        jMenuItemEdicaoFuncionario.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                CommonMethods.goToNewPage(currentFrame, new FormDadosFuncionarioEdicao(currentFrame, 1l));
            }
        });

        jMenuItemCadastroProjeto.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                CommonMethods.goToNewPage(currentFrame, new FormProjeto(currentFrame));
            }
        });
    }

}
