/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.faculdade.imepac.UI.listagem;

import br.com.faculdade.imepac.UI.cadastro.FormDadosFuncionario;
import br.com.faculdade.imepac.UI.cadastro.FormProjeto;
import br.com.faculdade.imepac.UI.commons.CommonMethods;
import br.com.faculdade.imepac.UI.edicao.FormDadosFuncionarioEdicao;
import br.com.faculdade.imepac.UI.edicao.FormProjetoEdicao;
import br.com.faculdade.imepac.UI.visualizar.VisualizarDadosFuncionario;
import br.com.faculdade.imepac.UI.visualizar.VisualizarDadosProjeto;
import br.com.faculdade.imepac.entidade.pessoa.Funcionario;
import br.com.faculdade.imepac.entidade.projeto.Projeto;
import br.com.faculdade.imepac.entidade.relacionamento.Relacionamento;
import br.com.faculdade.imepac.infraestrutura.JPAUtil;
import br.com.faculdade.imepac.infraestrutura.Persistence;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.List;
import java.util.Set;
import javax.persistence.EntityManager;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JViewport;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gusta
 */
public class ListagemProjetos extends javax.swing.JPanel {

    private Projeto projetoSelecionado;
    private JFrame frame;
    private List<Projeto> listaProjetos;

    /**
     * Creates new form ListagemFuncionarios
     */
    public ListagemProjetos(JFrame frame) {
        this.frame = frame;
        initComponents();
        inicializeTable();
        addActions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jButtonVerDadosFuncionario = new javax.swing.JButton();
        jButtonArquivar = new javax.swing.JButton();
        jButtonEdicao = new javax.swing.JButton();
        jButtonVerFuncionarios = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jTextFieldCampoBusca = new javax.swing.JTextField();
        jButtonLimparFiltro = new javax.swing.JButton();
        jCheckBoxStatus = new javax.swing.JCheckBox();
        jButtonVerDadosProjeto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProjetos = new javax.swing.JTable();

        jPasswordField1.setText("jPasswordField1");

        jButtonVerDadosFuncionario.setBackground(new java.awt.Color(0, 204, 204));
        jButtonVerDadosFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/olho.png"))); // NOI18N
        jButtonVerDadosFuncionario.setText("Visualizar");

        jButtonArquivar.setBackground(new java.awt.Color(204, 0, 0));
        jButtonArquivar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/funcionario-deletar-icone.png"))); // NOI18N
        jButtonArquivar.setText("Arquivar");

        jButtonEdicao.setBackground(new java.awt.Color(0, 102, 255));
        jButtonEdicao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icone-editar.png"))); // NOI18N
        jButtonEdicao.setText("Editar");

        jButtonVerFuncionarios.setBackground(new java.awt.Color(0, 102, 51));
        jButtonVerFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/lupa.png"))); // NOI18N
        jButtonVerFuncionarios.setText("Funcionarios");

        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/lupa (1).png"))); // NOI18N

        jTextFieldCampoBusca.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCampoBusca.setForeground(new java.awt.Color(0, 0, 0));

        jButtonLimparFiltro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/filtro.png"))); // NOI18N
        jButtonLimparFiltro.setText("Limpar");

        jCheckBoxStatus.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jCheckBoxStatus.setText("Arquivados");
        jCheckBoxStatus.setToolTipText("");

        jButtonVerDadosProjeto.setBackground(new java.awt.Color(0, 204, 204));
        jButtonVerDadosProjeto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/olho.png"))); // NOI18N
        jButtonVerDadosProjeto.setText("Visualizar");

        jTableProjetos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "CPF", "Nome"
            }
        ));
        jTableProjetos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jTableProjetos.setColumnSelectionAllowed(true);
        jTableProjetos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTableProjetos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonEdicao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonVerFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonVerDadosProjeto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonArquivar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonLimparFiltro)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxStatus))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCampoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 295, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldCampoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimparFiltro)
                    .addComponent(jCheckBoxStatus))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonVerDadosProjeto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonVerFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonArquivar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonArquivar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEdicao;
    private javax.swing.JButton jButtonLimparFiltro;
    private javax.swing.JButton jButtonVerDadosFuncionario;
    private javax.swing.JButton jButtonVerDadosProjeto;
    private javax.swing.JButton jButtonVerFuncionarios;
    private javax.swing.JCheckBox jCheckBoxStatus;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProjetos;
    private javax.swing.JTextField jTextFieldCampoBusca;
    // End of variables declaration//GEN-END:variables

    public void inicializeTable() {
        DefaultTableModel modelo = new DefaultTableModel();

        modelo.addColumn("CEP");
        modelo.addColumn("Nome");
        modelo.addColumn("Status");

        EntityManager em = JPAUtil.getEntityManager();
        Persistence ps = new Persistence(em);

        em.getTransaction().begin();
        this.listaProjetos = ps.getListEntity(Projeto.class);

        for (Projeto projeto : listaProjetos) {
            modelo.addRow(new Object[]{projeto.getCep(), projeto.getNome(), projeto.isArquivado()});
        }

        // Atribua o modelo de tabela à tabela
        jTableProjetos.setModel(modelo);

        // Permita seleção única de linha na tabela
        jTableProjetos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        // Adicione um ouvinte de seleção à tabela
        jTableProjetos.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    int selectedRow = jTableProjetos.getSelectedRow();
                    if (selectedRow != -1) { // Verifique se alguma linha está selecionada
                        // Recupere os dados da linha selecionada
                        int rowIndex = jTableProjetos.convertRowIndexToModel(selectedRow);
                        // Supondo que 'listaFuncionarios' esteja disponível neste contexto
                        projetoSelecionado = listaProjetos.get(rowIndex);
                        // Faça algo com o funcionarioSelecionado
                    }
                }
            }
        });
    }

    public void addActions() {

        jButtonEdicao.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                CommonMethods.goToNewPage(frame, new FormProjetoEdicao(frame, projetoSelecionado.getId()));
            }
        });

        jButtonArquivar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {

                    if (projetoSelecionado.isArquivado()) {
                        projetoSelecionado.setArquivado(false);
                    } else {
                        projetoSelecionado.setArquivado(true);
                    }

                    EntityManager em = JPAUtil.getEntityManager();
                    Persistence ps = new Persistence(em);

                    em.getTransaction().begin();
                    ps.updateEntity(projetoSelecionado);
                    em.getTransaction().commit();
                    em.close();
                    JOptionPane.showMessageDialog(null, "Status alterado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                    CommonMethods.goToNewPage(frame, new ListagemProjetos(frame));
                } catch (Exception erro) {
                    JOptionPane.showMessageDialog(null, "Ocorreu um erro! " + erro.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
        });

        jButtonVerFuncionarios.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                DefaultTableModel modelo = new DefaultTableModel();

                modelo.addColumn("CPF");
                modelo.addColumn("Nome");

                EntityManager em = JPAUtil.getEntityManager();
                Persistence ps = new Persistence(em);

                em.getTransaction().begin();

                var listaRelacionamento = ps.buscarRelacionamentosPorProjetoId(projetoSelecionado.getId());

                em.close();

                for (Relacionamento relacionamento : listaRelacionamento) {
                    if (relacionamento.getDataTermino() == null) {
                        modelo.addRow(new Object[]{relacionamento.getFuncionario().getCpf(),
                            relacionamento.getFuncionario().getNome()});
                    }
                }

                JTable table = new JTable(modelo);
                JScrollPane scrollPane = new JScrollPane(table);

                JFrame frame = new JFrame("Funcionário relacionados ao projeto");
                frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                frame.setSize(500, 300);
                frame.add(scrollPane);
                frame.setVisible(true);

            }
        });

        jButtonLimparFiltro.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jTextFieldCampoBusca.setText("");
                inicializeTable();
            }
        });

        jButtonVerDadosProjeto.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                JScrollPane scrollPane = new JScrollPane(new VisualizarDadosProjeto(frame, projetoSelecionado.getId()));

                scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
                scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);

                frame.getContentPane().removeAll();

                // Adiciona o JScrollPane ao frame
                frame.add(scrollPane, BorderLayout.CENTER);

                // Torna o frame visível
                frame.setVisible(true);
            }
        });

        jCheckBoxStatus.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent e) {
                DefaultTableModel modelo = new DefaultTableModel();

                modelo.addColumn("CEP");
                modelo.addColumn("Nome");
                modelo.addColumn("Status");

                if (e.getStateChange() == ItemEvent.SELECTED) {
                    for (Projeto projeto : listaProjetos) {
                        if (projeto.isArquivado() == false) {
                            modelo.addRow(new Object[]{projeto.getCep(), projeto.getNome(), projeto.isArquivado()});
                        }
                    }
                }
                if (e.getStateChange() != ItemEvent.SELECTED) {
                    for (Projeto projeto : listaProjetos) {
                        if (projeto.isArquivado() == true) {
                            modelo.addRow(new Object[]{projeto.getCep(), projeto.getNome()});
                        }
                    }
                }
                jTableProjetos.setModel(modelo);
            }
        });

        jButtonBuscar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                var valorBusca = jTextFieldCampoBusca.getText();

                EntityManager em = JPAUtil.getEntityManager();
                Persistence ps = new Persistence(em);

                var status = jCheckBoxStatus.isSelected();

                em.getTransaction().begin();
                listaProjetos = ps.getListProjetos(valorBusca, !status);

                DefaultTableModel modelo = new DefaultTableModel();

                modelo.addColumn("CPF");
                modelo.addColumn("Nome");

                for (Projeto projeto : listaProjetos) {
                    modelo.addRow(new Object[]{projeto.getCep(),
                        projeto.getNome()});
                }

                jTableProjetos.setModel(modelo);
            }
        });

    }
}
